"""new fields in user model

Revision ID: 27033b9fb844
Revises: 0be9916b5df2
Create Date: 2021-09-06 16:23:08.022674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27033b9fb844'
down_revision = '0be9916b5df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
